### PR TITLE
Remove bls private key

### PR DESCRIPTION
**Pull request by richardkiss**
Got rid of `BLSPrivateKey` in favor of just passing around secret exponents, since they're just ints anyway.

### CODE REVIEW

**Comment by mariano54** [comment]
Two small things to point out: blspy keys already have fingerprint methods. Also, you can use bytes(blspy object) instead of.serialize()

**Comment by richardkiss** [comment]
The only `serialize` I added was on `blspy.PrivateKey`, which doesn't seem to respond to `bytes(x)`, at least in 0.1.8. Let me try 0.1.14.

**Comment by richardkiss** [comment]
Works in 0.1.14, so I'll update requirements to that.

**Comment by richardkiss** [comment]
Since there are conflicts, I'm redoing this patch in a different branch.

**Pull request closed without merging**
